### ISSUE TITLE
Secure domain name, create website, after name is secured.

### ISSUE THREAD

**Issue by ak-org** [ak-org/rend_ez_vous#11]

**Comment by dstocke22** [comment]
Chosen Name, in progress

**Comment by ak-org** [comment]
Domains acquired, hosted app on heroku. currently redirecting domain to the hosted app.

**Comment by ak-org** [comment]
Create a stage environment on azure for internal beta testing.

**Comment by ak-org** [comment]
Complete. We have secured domains, and we can run it as SSL on heroku.
